name: gan2
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.1.1
  firebase_core: ^0.4.3+3
  firebase_storage: ^3.1.5
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.4+2
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.0.0
  meta: ^1.1.6
  ansicolor: ^1.0.2
  font_awesome_flutter: ^8.4.0
  flutter_speed_dial: ^1.2.5
  image_picker: ^0.6.5
  image_cropper: ^1.2.1
  pull_to_refresh: ^1.5.8
  image: ^2.1.12
  path_provider: ^1.6.8
  rxdart: ^0.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Medium.ttf
        - asset: lib/fonts/Montserrat-Light.ttf
        - asset: lib/fonts/Montserrat-Regular.ttf

  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
